(dp1
S'output'
p2
S"<type 'exceptions.IndexError'> list index out of range"
p3
sS'layer'
p4
S'/home/yasaswi/web2py/applications/dummy/controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 0x7eff9c4f54b0, file "/home/yasaswi/web2py/applications/dummy/controllers/default.py:index", line 10>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/yasaswi/web2py/gluon/restricted.py", line 216, in restricted\n    exec(ccode, environment)\n  File "/home/yasaswi/web2py/applications/dummy/controllers/default.py:index", line 62, in <module>\n  File "/home/yasaswi/web2py/gluon/globals.py", line 405, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/yasaswi/web2py/applications/dummy/controllers/default.py:index", line 17, in index\n  File "/home/yasaswi/web2py/applications/dummy/controllers/default.py:index", line 37, in fetch_file\nIndexError: list index out of range\n'
p11
s.